name: Python package

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
    pr-lint:
      runs-on: ubuntu-latest
      steps:
      - uses: seferov/pr-lint-action@master
        with:
          # Conventional Commits format
          title-regex: '^(revert: )?((feat|fix|docs|style|refactor|perf|test|chore|improvement|build|ci|wip)(\(.+\))?: )*(.*$)'
          title-regex-flags: 'g'
  
